name: Auto Create Pull Request

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  auto-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: "main"
          pr_title: "feat: ${{ github.ref_name }} changes"
          pr_body: |
            🔄 Automatycznie wygenerowany Pull Request z brancha: **${{ github.ref_name }}**
            
            ### Zmiany zawierają:
            ${{ github.event.head_commit.message }}
            
            ### Branch źródłowy:
            `${{ github.ref_name }}`
            
            ### Autor:
            @${{ github.actor }}
          pr_label: "automated-pr"
          pr_draft: false
          pr_allow_empty: false
